### PR TITLE
Updates to latest MTK and SymbolicUtils

### PR DESCRIPTION
**Pull request by YingboMa**

### CODE REVIEW

**Comment by YingboMa** [comment]
@isaacsas could you take a look at the test failure?

**Comment by isaacsas** [comment]
Will take a look tomorrow.

**Comment by isaacsas** [comment]
@YingboMa this seems overly restrictive:

https://github.com/SciML/ModelingToolkit.jl/blob/fdb4770518c6a66006a6d954c66bfd6ebc97566a/src/systems/abstractsystem.jl#L670-L674

Why should the number of states have to equal the number of equations? For example, imagine a hybrid model with four states, three defined as ODEs and the fourth a jump process. That wouldn't pass this check. 

Could it be changed to the number of equations being `<=` the number of states?

**Comment by YingboMa** [comment]
Yeah, we should have a way to disable the test. We need to have that test by default though. People write a lot of wrong code, and we need to catch that early.

**Comment by isaacsas** [comment]
That’s the issue here since the network has an extra state in its definition that is not used, and so Catalyst generates no ODE for it.

**Pull request merged**
